name: battery_plus_windows
description: An implementation for the web platform of the Flutter `battery_plus_windows` plugin.
version: 1.0.0
homepage: https://github.com/fluttercommunity/battery_plus/battery_plus_windows

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  battery_plus_platform_interface:
    path: ../battery_plus_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: BatteryPlusWindowsPlugin
