name: package_info_plus
description: Flutter plugin for querying information about the application
  package, such as CFBundleVersion on iOS or versionCode on Android.
homepage: https://github.com/fluttercommunity/package_info_plus
# 0.4.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.4.5

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.packageinfo
        pluginClass: PackageInfoPlugin
      ios:
        pluginClass: FLTPackageInfoPlugin
      macos:
        default_package: package_info_plus_macos
      web:
        default_package: package_info_plus_web
      windows:
        default_package: package_info_plus_windows
  
dependencies:
  flutter:
    sdk: flutter
  package_info_plus_platform_interface:
    path: ../package_info_plus_platform_interface
  package_info_plus_web:
    path: ../package_info_plus_web
  package_info_plus_macos:
    path: ../package_info_plus_macos
  package_info_plus_windows:
    path: ../package_info_plus_windows
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  integration_test: ^0.8.0
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
