name: battery_plus_linux
description: Linux implementation of the battery_plus plugin
homepage: https://github.com/fluttercommunity/battery_plus/battery_plus_linux
version: 1.0.0

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: BatteryLinux
        pluginClass: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  battery_plus_platform_interface:
    path: ../battery_plus_platform_interface
  dbus: ^0.0.0-dev.19
  meta: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2
  pedantic: ^1.9.2
