name: battery_plus_linux
description: Linux implementation of the battery_plus plugin
homepage: https://github.com/fluttercommunity/battery_plus/battery_plus_linux
version: 1.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: BatteryPlusLinuxPlugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2
