name: battery_plus_macos
description: A new flutter plugin project.
version: 1.0.0
homepage: https://github.com/fluttercommunity/battery_plus/battery_plus_for_web/experimental_battery_web


environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.4'


dependencies:
  battery_plus_platform_interface:
    path: ../battery_plus_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      macos:
        pluginClass: BatteryPlusMacosPlugin
        fileName: battery_plus_macos.dart
